/* Exercise 6-7.c
 *
 * Prime numbers can also be generated by an algorithm known as the
 * Sieve of Eratosthenes. The algorithm for this procedure is presented
 * here. Write a program that implements this algorithm. Have the
 * program find all prime numbers up to n = 150.

*/